# Generated by Django 4.2.19 on 2025-03-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendor", "0001_initial"),
        ("store", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="coupon",
            unique_together={("vendor", "code")},
        ),
    ]
