# Generated by Django 4.2.19 on 2025-03-06 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_alter_coupon_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-date"], "verbose_name_plural": "Notification"},
        ),
    ]
